apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: chatapp

spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: /data